import ThemeRegistry from '@/components/ThemeRegistry'
import { Button } from '@mui/material'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <main>
          <ThemeRegistry options={{ key: 'mui' }}>
            {children}
            <Button>Break</Button>
          </ThemeRegistry>
        </main>
      </body>
    </html>
  )
}
